# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lottieloader' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for lottieloader
  pod 'AppCenter/Crashes', '~> 1.1.0'
  pod 'AppCenter/Analytics', '~> 1.1.0'
  pod 'AppCenterReactNativeShared', '~> 1.1.0'

  

  target 'lottieloaderTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'lottieloader-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for lottieloader-tvOS

  target 'lottieloader-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
